//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        public DonDatHang()
        {
            this.ChiTietDonDatHang = new HashSet<ChiTietDonDatHang>();
        }
    
        public int MaDDH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<bool> TinhTrangGiaoHang { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<bool> DaThanhToan { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> UuDai { get; set; }
        public Nullable<bool> DaHuy { get; set; }
        public Nullable<bool> DaXoa { get; set; }
    
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
